# Generated by Django 6.0.4 on 2026-04-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='conversion_type',
            field=models.CharField(choices=[('pdf_to_word', 'PDF to Word'), ('pdf_to_excel', 'PDF to Excel'), ('pdf_to_jpg', 'PDF to JPG'), ('pdf_to_txt', 'PDF to TXT'), ('word_to_pdf', 'Word to PDF'), ('excel_to_pdf', 'Excel to PDF'), ('ppt_to_pdf', 'PPT to PDF'), ('jpg_to_pdf', 'JPG to PDF'), ('txt_to_pdf', 'TXT to PDF'), ('html_to_pdf', 'HTML to PDF')], default='word_to_pdf', max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='converted_file',
            field=models.FileField(blank=True, null=True, upload_to='converted/'),
        ),
    ]
